swagger: "2.0"
info:
  description: "Descrição da aplicação"
  version: "1.0.0"
  title: "Minha Aplicação"
  contact:
    email: "desenvolvedor@oi.net.br"
host: "localhost:8094"
basePath: "/my-application"
schemes:
- "http"
paths:
  /cliente/{nome}:
    get:
      summary: "Carrega um cliente pelo nome"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: path
        name: "nome"
        description: "Nome do cliente a ser carregado"
        required: true
        type: string
      - in: header
        name: x-origin-application
        description: "Nome da aplicação origem da requisição. Ex: my-application"
        type: string
        required: true
      - in: header
        name: x-origin-channel
        description: "Nome do canal origem da requisição. Ex: app-ios"
        type: string
        required: true
      responses:
        200:
          description: "Cliente carregado com sucesso"
        400:
          description: "Campos obrigatórios não preenchidos"
        401:
          description: "Não autorizado, token de autenticação não foi enviado"
        403:
          description: "Acesso negado, token inválido."
        412:
          description: "Headers de origem não enviados."
      security:
        - api_key: []  
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "Authorization"
    in: "header"
externalDocs:
  description: "Minha Aplicação"
  url: "http://swagger.io"